### ISSUE TITLE
glottis on/off etc.

### ISSUE THREAD

**Issue by belm0** [PaulBatchelor/voc#2]
I may be missing it, but there doesn't seem to be a way to turn off the glottis with the current API.  Pink Trombone (w/ "always voice" = off) activates glottis by touch of the voice box area and applies a suitable attack and decay.  This is essential for mimicking speech.

**Comment by PaulBatchelor** [comment]
I typically use Voc in modular environments such as Sporth, where I can use several kinds of line and envelope generators for articulation.

**Comment by belm0** [comment]
It's important that the envelope be applied at the glottis output (before tract reflections etc.) rather than end of the tract.  I see that voc supports arbitrary glottis input, but for completeness of the built-in glottis it would be great to have on/off capability.  A natural thing to do with glottis is tie it to MIDI control etc. where on/off is common.

**Comment by PaulBatchelor** [comment]
I can add a simple toggle with some smoothing to prevent clicks. Would that be sufficient?

**Comment by belm0** [comment]
I can try a pull request.

PT glottis attack & decay is hard-coded here:  https://github.com/giuliomoro/pink-trombone/blob/bela/trombone.js#L754

The constants work out to 90ms attack and 230 ms decay.
