### ISSUE TITLE
cwebmac.tex dependency is heavy

### ISSUE THREAD

**Issue by belm0** [PaulBatchelor/voc#6]
Build of voc.pdf appears to need cwebmac.tex, which on Ubuntu requires manual install of both texlive-extra-utils and texlive-formats-extra, pulling in dozens of packages, some being very large in size.

(Minor correction to README.md: by default make does not build the PDF.)

Just wanted to note this should it be straightforward to remove the dependency.

Overall I've found contributing to voc C source very time consuming due to the literate programming framework and dependencies.  Not sure it's a win in current form-- I would be ecstatic for simple well-documented C source.

**Comment by PaulBatchelor** [comment]
> Build of voc.pdf appears to need cwebmac.tex, which on Ubuntu requires manual install of both texlive-extra-utils and texlive-formats-extra, pulling in dozens of packages, some being very large in size.

This is not a Voc issue, or even a CWEB issue, but an issue with the Ubuntu package manager. 

> (Minor correction to README.md: by default make does not build the PDF.)

I updated this, "make pdf" generates the pdf now. I will update the README accordingly. 

> Just wanted to note this should it be straightforward to remove the dependency.

This is built into the tex generation. I would have to remove CWEB entirely to remove it.

> Overall I've found contributing to voc C source very time consuming due to the literate programming framework and dependencies. 

In the short run, yes, it feels sluggish to hack on. However, in the long run, I believe this approach will greatly benefit future code divers who wish to understand the concepts and motivations behind the code. 

> I would be ecstatic for simple well-documented C source.

Not going to happen. There really isn't any good way to document DSP code using simple comments alone. I really, *really* need mathematical notation and visuals to understand some of the concepts and derivations happening in the code, and TeX adequately provides these things. I'm also using BibTeX to cite academic sources that discuss the concepts in greater detail.

If you are frustrated, you can always fork my project. My licenses are very generous.
